---
all:
  children:

    linux:
      children:
        debian:
          hosts:
            ManagedNode1:
              ansible_host: 10.10.10.91
              ansible_user: wilder
              ansible_ssh_private_key_file: /home/sysadmin/.ssh/id_ed25519_Test_Ansible
            srv-proxy:
              ansible_host: 192.168.10.20
        ubuntu:
          hosts:
            srv-wazuh:
              ansible_host: 192.168.10.30
              ansible_user: root

    windows:
      children:
        ad:
          hosts:
            dc01:
              ansible_host: 192.168.20.10
              ansible_user: Administrateur
              ansible_password: "MotDePasse!"
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
        clients:
          hosts:
            win10-01:
              ansible_host: 192.168.20.50
              ansible_connection: winrm

    reseau:
      children:
        firewalls:
          hosts:
            pf-fw-01:
              ansible_host: 192.168.1.1
              ansible_connection: network_cli
              ansible_network_os: vyos
              ansible_user: admin
              ansible_password: admin123
        switchs:
          hosts:
            sw-core-01:
              ansible_host: 192.168.1.2
              ansible_connection: network_cli
              ansible_network_os: ios
              ansible_user: cisco
              ansible_password: cisco123
        bornes_wifi:
          hosts:
            ap-01:
              ansible_host: 192.168.1.3
              ansible_connection: httpapi
              ansible_httpapi_use_ssl: true
              ansible_httpapi_validate_certs: false

    services:
      children:
        glpi:
          hosts:
            srv-glpi:
        wazuh:
          hosts:
            srv-wazuh:
        proxy:
          hosts:
            srv-proxy:
        ad:
          hosts:
            dc01
        dns:
          hosts:
            dc01
        dhcp:
          hosts:
            dc01
        stockage:
          hosts:
            nas01:
              ansible_host: 192.168.30.5

